### ISSUE TITLE
Links in master file

### ISSUE THREAD

**Issue by epaulski** [epaulski/Gameverse#1]
Links are broken. Since the master file is in the root folder, and files such as registration.aspx have been moved to the Code folder, the links in the body tag of the master file no longer work.

![image](https://cloud.githubusercontent.com/assets/12277528/13311086/2fe6ba48-db51-11e5-81f5-51d151301be7.png)

**Comment by epaulski** [comment]
Note: trying to add ../ or ~/ in front of a url (like href="~/index.aspx") does not work.

**Comment by aebone** [comment]
Hi, I included "../" on the master page links, I think it is working now. Can you check? Because you said you did it. If the problem remains we can just move the index into the Code folder.

**Comment by epaulski** [comment]
I won't be able to test it out until later tonight, but I believe I already tried that. The problem is, if you start from index and you click ../index.aspx, you get an error since you are already in root

**Comment by epaulski** [comment]
Maybe it would be better to move the master page to the Code folder? That way, we can replace index to the full path (assuming we set a standard local host port)

**Comment by epaulski** [comment]
I've sent the professor a question about this
